version: 1

update_configs:
    -   package_manager: 'php:composer'
        directory: '/dev-tools'
        update_schedule: 'live'
        default_assignees:
            - 'kubawerlos'
        ignored_updates:
            -   match:
                    dependency_name: 'php-cs-fixer/diff'
        automerged_updates:
            -   match:
                    dependency_type: 'all'
                    update_type: 'all'
        version_requirement_updates: 'increase_versions'
